### ISSUE TITLE
Make it work on region pages

### ISSUE THREAD

**Issue by gurmanbh** [reuters-graphics/chart-module-weeklyaverage#7]

**Comment by hobbes7878** [comment]
Working on this, I noticed that this chart is sensitive to the sort order of the data. So for example, I had region data that was by default sorted latest to first date, and it didn't work. No biggie to sort it on my end, by probably something the chart should handle.

**Comment by gurmanbh** [comment]
hmmm. Interesting. Dont know why that should effect anything.
